### ISSUE TITLE
 error using `hashed_password()'  when using mariadb_user from cookbook

### ISSUE THREAD

**Issue by corbesero** [sous-chefs/mariadb#237]
### Cookbook version
1.5.4

### Chef-client version
13.8.5

### Platform Details
centos 7.4

### Scenario:
I am trying to create a user..  using the hashed password.  I am doing this in a wrapper cookbook.
Follow up question: how do I create the hashed password?  Do I execute a `select PASSWORD('xyzzy'))`?

### Steps to Reproduce:
The example from the README fails.

```
mariadb_user 'disenfranchised' do
  password hashed_password('md5eacdbf8d9847a76978bd515fae200a2a')
  action :create
end
```

### Expected Result:
The resource to execute without error.

### Actual Result:

       NoMethodError
       -------------
       undefined method `hashed_password' for Custom resource mariadb_user from cookbook mariadb
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/sncr_act3_mariadb/recipes/_create_db_users.rb:10:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/sncr_act3_mariadb/recipes/_create_db_users.rb:9:in `from_file'
         /tmp/kitchen/cache/cookbooks/sncr_act3_mariadb/recipes/server.rb:70:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/sncr_act3_mariadb/recipes/_create_db_users.rb:
       
         3:  # Recipe:: _create_db_users
         4:  #
         5:  # Copyright:: 2019, Synchronoss Technologies, Inc., All Rights Reserved.
         6:  
         7:  db_users = node['sncr_act3_mariadb']['db_users']
         8:  
         9:  mariadb_user 'disenfranchised' do
        10>>   password hashed_password('md5eacdbf8d9847a76978bd515fae200a2a')

**Comment by sinfomicien** [comment]
Hi dear @corbesero,

The main problem here... The 1.5.4 version of the cookbook is hard to debug for me now. 

If you could work on it, i will create a 1.5.x branch where i import the tag v1.5.4, and could perhaps create a 1.5.5 version of the cookbook if you submit a PR. But it's up to you, as i got big lack of time these days.

**Comment by corbesero** [comment]
I'm sorry.  I never noticed your reply.  
I am going to start using the 3.x cookbook versions.

**Comment by corbesero** [comment]
I have the same question/issue with the 3.1.0 cookbook.  How do I make the hashed_password() function available in my recipe?

```
mariadb_user 'pacwriter' do
  action :create
  password hashed_password('*3D3B92F242033365AE5BC6A8E6FC3E1679F4140A')
  ctrl_password node['sncr_pac_mariadb']['password']
end
```

**Comment by ramereth** [comment]
@corbesero if you do something like this in your recipe, it should work:
```ruby
::Chef::DSL::Recipe.include HashedPassword::Helper
```

**Comment by kevbotto** [comment]
Hello, 

Not sure if this has recently changed but the provided solution doesn't seem to work, and I've tried alternative methods like
`Chef::DSL::Recipe.send(:include, HashedPassword::Helper)` or `Chef::Recipe.include(HashedPassword::Helper)`

The error is still `NoMethodError: undefined method 'hashed_password' for Custom resource mariadb_user from cookbook mariadb`
